name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build # Adjust this step based on your build script

    - name: Zip codebase
      run: zip -r deploy.zip .

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }} # Adjust to your AWS region
        APPLICATION_NAME: 'my-application' # Your Elastic Beanstalk application name
        ENVIRONMENT_NAME: 'my-environment' # Your Elastic Beanstalk environment name
      run: |
        # Install the AWS CLI
        pip install awscli
        # Deploy the zip file to Elastic Beanstalk
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$APPLICATION_NAME,S3Key=$GITHUB_SHA.zip
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
