name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Zip codebase
      run: zip -r deploy.zip .

    - name: Deploy to AWS Elastic BeanTalk
    uses: einaregilsson/beanstalk-deploy@v20
    with:
    aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    application_name: admin-client
    environment_name: Adminclient-env
    version_label: ${{ env.PIPELINE_ID }}
    use_existing_version_if_available: true
    region: ${{ env.AWS_REGION }}
    deployment_package: deploy.zip

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: zed-facilitator # Your Elastic Beanstalk application name
        environment_name: zed-facilitator-env # Your Elastic Beanstalk environment name
        version_label: ${{ github.sha }}
        use_existing_version_if_available: true
        region: us-east-2
        deployment_package: deploy.zip