name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Zip codebase
      run: zip -r deploy.zip .

    - name: Verify AWS Secrets
      run: |
        echo "AWS Access Key ID ends with: ${AWS_ACCESS_KEY_ID: -4}"
        echo "AWS Secret Access Key ends with: ${AWS_SECRET_ACCESS_KEY: -4}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: zed-facilitator # Your Elastic Beanstalk application name
        environment_name: zed-facilitator-env # Your Elastic Beanstalk environment name
        version_label: ${{ github.sha }}
        use_existing_version_if_available: true
        region: us-east-2
        deployment_package: deploy.zip