name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Zip codebase
      run: zip -r deploy.zip .

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
        APPLICATION_NAME: 'zed-facilitator' # Your Elastic Beanstalk application name
        ENVIRONMENT_NAME: 'zed-facilitator' # Your Elastic Beanstalk environment name
      run: |
        # Install the AWS CLI
        pip install awscli
        # Deploy the zip file to Elastic Beanstalk
      # Install the AWS CLI
        pip install awscli
        # Create S3 bucket if it doesn't exist
        if ! aws s3api head-bucket --bucket $S3_BUCKET --region $AWS_REGION 2>/dev/null; then
          aws s3api create-bucket --bucket $S3_BUCKET --region $AWS_REGION --create-bucket-configuration LocationConstraint=$AWS_REGION
        fi
        # Upload the zip file to S3
        aws s3 cp deploy.zip s3://$S3_BUCKET/$GITHUB_SHA.zip --region $AWS_REGION
        # Deploy the zip file to Elastic Beanstalk
        aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$S3_BUCKET,S3Key=$GITHUB_SHA.zip --region $AWS_REGION
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA --region $AWS_REGION